# Generated by Django 4.2.10 on 2024-02-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsychoType',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ptypes', models.ManyToManyField(to='testapp.psychotype')),
            ],
        ),
    ]
